TASK:
  NAME: "Baseline"
  NOTES: "KaggleVersion_Notes"
  TAGS: ["dev", "train"]  
  MODE: "train"  # train / visualization
  DEVICE: "cuda"  
  SEED: 1

MODEL:
  MODULE: "Lucky"   # Lucky / Baseline
  BACKBONE_TYPE: "resnet50_ibn_a" # resnet50 / resnet50_ibn_a
  BACKBONE_FEATURES_DIM: 2048


DATASET:
  TRAIN_DATASET: "sysu_mm01"
  TRAIN_DATASET_PATH: "/kaggle/input/occluded-duke/Occluded_Duke"
  MODE: "all"


DATALOADER:
  IMAGE_SIZE: [384, 192]
  BATCHSIZE: 4
  NUM_INSTANCES: 8
  TEST_BATCH: 64

OPTIMIZER:
  TOTAL_TRAIN_EPOCH: 81
  LEARNING_RATE: 0.1

SCHEDULER:
  MILESTONES: [10, 20, 50]   
  FACTORS: [1.0, 0.1, 0.01]  

TEST:
  EVAL_EPOCH: 2
  RESUME_TEST_MODEL: 119  
  TEST_MODE: "inter-camera"  # inter-camera, intra-camera, all

SAVE:
  OUTPUT_PATH: "results/outputs"
  MAX_SAVE_MODEL_NUM: 1 # 最多保存的模型数量

