TASK:
  NAME: "Method_Name"
  NOTES: "KaggleVersion_Notes"
  PROJECT: "VI_ReID"
  TAGS: ["dev", "train"]  
  MODE: "train"  # train / visualization
  DEVICE: "cuda"  
  SEED: 1

MODEL:
  MODULE: "Lucky"   # Lucky / Baseline
  BACKBONE_TYPE: "resnet50" # resnet50 / resnet50_ibn_a
  BACKBONE_FEATURES_DIM: 2048


DATASET:
  TRAIN_DATASET: "sysu_mm01"
  TRAIN_DATASET_PATH: "/kaggle/input/sysu-mm01/SYSU_MM01/"
  MODE: "all"


DATALOADER:
  IMAGE_SIZE: [288, 144]
  BATCHSIZE: 8
  NUM_INSTANCES: 4
  TEST_BATCH: 64

# OPTIMIZER:
#   NAME: "SGD"
#   TOTAL_TRAIN_EPOCH: 55
#   LEARNING_RATE: 0.1

# SCHEDULER:
#   NAME: "Adjust_Learning_Rate"
  
OPTIMIZER:
  NAME: "Adam"
  TOTAL_TRAIN_EPOCH: 80
  LEARNING_RATE: 0.0035 

SCHEDULER:
  NAME: "WarmupMultiStepLR"

TEST:
  EVAL_EPOCH: 2
  RESUME_TEST_MODEL: 119  
  TEST_MODE: "inter-camera" 

SAVE:
  OUTPUT_PATH: "results/outputs"

